"""
user_id fk on_delete=CASCADE

Revision ID: 06babde93584
Revises: c2969b26c2cd
Create Date: 2022-04-14 13:17:05.813617
"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '06babde93584'
down_revision = 'c2969b26c2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stats_user_id_fkey', 'stats', type_='foreignkey')
    op.create_foreign_key(None, 'stats', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.create_foreign_key('stats_user_id_fkey', 'stats', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
