"""
user.login unique=True

Revision ID: c2969b26c2cd
Revises: d16a3777914f
Create Date: 2022-04-14 12:38:50.652078
"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'c2969b26c2cd'
down_revision = 'd16a3777914f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'repo_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('stats', 'repo_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
